export { newId } from './id.js';
export {
  IdSchema,
  type Id,
} from './shared/primitives.js';
export {
  AttachmentSchema,
  FileAttachmentSchema,
  CodeAttachmentSchema,
  VizAttachmentSchema,
  type Attachment,
  type FileAttachment,
  type CodeAttachment,
  type VizAttachment,
} from './shared/attachment.js';
export {
  VizEngineSchema,
  type VizEngine,
} from './shared/viz.js';


export {
  QuestionSchema,
  type Question,
  SingleChoiceQuestionSchema,
  OptionSchema,
  type SingleChoiceQuestion,
  type Option,
  MultipleChoiceQuestionSchema,
  type MultipleChoiceQuestion,
  ShortTextQuestionSchema,
  type ShortTextQuestion,
  LongTextQuestionSchema,
  type LongTextQuestion,
  DropdownQuestionSchema,
  type DropdownQuestion,
  FillGapsQuestionSchema,
  FillGapsPartSchema,
  TextPartSchema,
  TextGapPartSchema,
  DropdownGapPartSchema,
  type FillGapsQuestion,
  type FillGapsPart,
  type TextPart,
  type TextGapPart,
  type DropdownGapPart,
  MatchQuestionSchema,
  MatchOptionSchema,
  type MatchQuestion,
  type MatchOption,
  ScaleQuestionSchema,
  type ScaleQuestion,
  SortingQuestionSchema,
  SortItemSchema,
  type SortingQuestion,
  type SortItem,
  UploadQuestionSchema,
  FileKindSchema,
  type UploadQuestion,
  type FileKind,
} from './questions/index.js';

export {
  AnswerSchema,
  type Answer,
  SingleChoiceAnswerSchema,
  type SingleChoiceAnswer,
  MultipleChoiceAnswerSchema,
  type MultipleChoiceAnswer,
  ShortTextAnswerSchema,
  type ShortTextAnswer,
  LongTextAnswerSchema,
  type LongTextAnswer,
  DropdownAnswerSchema,
  type DropdownAnswer,
  FillGapsAnswerSchema,
  type FillGapsAnswer,
  MatchAnswerSchema,
  MatchPairSchema,
  type MatchAnswer,
  type MatchPair,
  ScaleAnswerSchema,
  type ScaleAnswer,
  SortingAnswerSchema,
  type SortingAnswer,
  UploadAnswerSchema,
  UploadedFileSchema,
  type UploadAnswer,
  type UploadedFile,
} from './answers/index.js';

export {
  QuizSchema,
  type Quiz,
  QuizDefinitionSchema,
  type QuizDefinition,
} from './quiz.js';
